# Generated by Django 4.2.4 on 2023-12-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('transit_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(default='info@enigmatix.io', max_length=254)),
                ('bank_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bankmodel')),
            ],
        ),
    ]
