# Generated by Django 4.2.4 on 2023-12-23 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmodel',
            name='last_modefied',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
