# Generated by Django 4.2.4 on 2023-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branchmodel_last_modefied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='last_modefied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
