# Generated by Django 4.2.4 on 2023-12-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branchmodel_last_modefied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='email',
            field=models.EmailField(default='admin@enigmatix.io', max_length=254),
        ),
    ]
